name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:8
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd glb_backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd glb_model_viewer
          npm install

      - name: Run backend tests (optional)
        run: |
          cd glb_backend
          echo "No tests configured yet"

      - name: Build frontend (optional)
        run: |
          cd glb_model_viewer
          npm run build
